// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdfpzdsd_24ARVHZt__muG8Z5RV6XPTBs',
    appId: '1:309163322544:web:4963319938161f182e1f75',
    messagingSenderId: '309163322544',
    projectId: 'jobu-993ae',
    authDomain: 'jobu-993ae.firebaseapp.com',
    storageBucket: 'jobu-993ae.appspot.com',
    measurementId: 'G-RD24P1339D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpsFDvRho9tAVJ2qJfKvrJisG-DrTvqwY',
    appId: '1:309163322544:android:afcafcb46f93f6a32e1f75',
    messagingSenderId: '309163322544',
    projectId: 'jobu-993ae',
    storageBucket: 'jobu-993ae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDs8SS0Fwqo21ZJDT3SQLhu8z50a2WHTdU',
    appId: '1:309163322544:ios:7dc432b347e43ddb2e1f75',
    messagingSenderId: '309163322544',
    projectId: 'jobu-993ae',
    storageBucket: 'jobu-993ae.appspot.com',
    iosClientId: '309163322544-2kti42j82hos34j6ff8ov3lie5s3udk9.apps.googleusercontent.com',
    iosBundleId: 'com.example.jobuapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDs8SS0Fwqo21ZJDT3SQLhu8z50a2WHTdU',
    appId: '1:309163322544:ios:7dc432b347e43ddb2e1f75',
    messagingSenderId: '309163322544',
    projectId: 'jobu-993ae',
    storageBucket: 'jobu-993ae.appspot.com',
    iosClientId: '309163322544-2kti42j82hos34j6ff8ov3lie5s3udk9.apps.googleusercontent.com',
    iosBundleId: 'com.example.jobuapp',
  );
}
